# This is the docker-compose script for local development.
# For the latest version of the docker images see:
# https://github.com/Azure/pcs-cli/blob/master/remotemonitoring/single-vm/docker-compose.dotnet.yml
#
# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - note how this file references many environment variables, either set
#   them in the .env file or edit this file adding the values here
# - run `docker-compose up`
# - open the browser at http://127.0.0.1:10443
#
# For more information see
# https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

version: "3"

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:testing
    ports:
      - "8080:10080"
    depends_on:
      - webui
      - auth-svc
      - iothub-manager-svc
      - devicesimulation
      - telemetry-svc
      - config-svc
    volumes:
      - ./config/nginx.conf:/app/config/nginx.conf:ro

  webui:
    image: rbachala/pcs-remote-monitoring-webui:1.0.6
    ports:
      - "443:443"
    depends_on:
      - auth-svc
      - iothub-manager-svc
      - devicesimulation
      - telemetry-svc
      - config-svc
      - diagnostics
  # NOTE: Volumes disabled for local development, uncomment if enabling auth
  # volumes:
  #   - ./webui-config.js:/app/build/webui-config.js:ro

  auth-svc:
    image: azureiotpcs/pcs-auth-dotnet:testing
    ports:
      - "9001:9001"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  iothub-manager-svc:
    image: rbachala/iothub-manager-dotnet:1.0.4
    ports:
      - "9002:9002"
    depends_on:
      - auth-svc
      - storage-adapter-svc
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:DS-1.0.6
    depends_on:
      - storage-adapter-svc
    ports:
      - "9003:9003"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
  # How one could mount custom device models
  # NOTE: Volumes disabled for local development
  # volumes:
  #   - ./my-device-models:/app/data:ro

  telemetry-svc:
    image: rbachala/telemetry-dotnet:1.0.0
    ports:
      - "9004:9004"
    depends_on:
      - auth-svc
      - storage-adapter-svc
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  config-svc:
    image: rbachala/pcs-config-dotnet:1.0.0
    ports:
      - "9005:9005"
    depends_on:
      - auth-svc
      - storage-adapter-svc
      - devicesimulation
      - telemetry-svc
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  storage-adapter-svc:
    image: rbachala/pcs-storage-adapter-dotnet:1.0.0
    ports:
      - "9022:9022"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  asamanager:
    image: rbachala/asa-manager-dotnet:1.0.0
    depends_on:
      - telemetry-svc
      - iothub-manager-svc
      - config-svc
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  diagnostics:
    image: azureiotpcs/pcs-diagnostics-dotnet:testing
    depends_on:
      - config-svc
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
